services:
  pg:
    restart: always
    # image: postgis/postgis:latest
    image: postgres:17
    container_name: "pg"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  pg_data: {}
